### PR TITLE
feat: supabase-traefik up-to-date solution

### PR DESCRIPTION
**Pull request by NorkzYT**
## What kind of change does this PR introduce?

Docs update with latest up-to-date Supabase Docker and Traefik Config.

### Related Discussion
https://github.com/orgs/supabase/discussions/11228#discussioncomment-4727494

### CODE REVIEW

**Comment by Coderwelsch** [comment]
Damn, the last PR is one year ago. Where is the author of this repo?!

**Comment by NorkzYT** [comment]
> Damn, the last PR is one year ago. Where is the author of this repo?!


The only commit to this repo is by @soedirgo which looks like they are a member of `@supabase`. Hopefully they review within a month.

**Comment by soedirgo** [comment]
Thanks @NorkzYT!

**Comment by NorkzYT** [comment]
> Thanks @NorkzYT!

No problem, thank you for reviewing and merging.

**Pull request merged**
